version: '3.8'

services:
  group12-postgres:
    build: .
    container_name: group12-postgres
    env_file:
    - .env
    volumes:
      - ./schemas:/schemas
      - ./init:/docker-entrypoint-initdb.d
      - ./data/${SCALE}/:/data
      - ./queries/${SCALE}/:/queries
      - group12-pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    command: >
      postgres
      -c max_wal_size=2GB
      -c checkpoint_timeout=15min
       
volumes:
  group12-pgdata: