version: '3.8'

services:
  group12-postgres:
    build: .
    container_name: group12-postgres
    environment:
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_DB=$POSTGRES_DB
    - SCALE=$SCALE
    - INDEX_ALL=$INDEX_ALL
    - INDEX_DATES=$INDEX_DATES
    - INDEX_NUMBERS=$INDEX_NUMBERS
    - INDEX_TEXT=$INDEX_TEXT
    volumes:
      - ./scripts:/scripts
      - ./schema.sql:/schema.sql
      - ./data/${SCALE}/:/data
      - ./queries/${SCALE}/:/queries
      - group12-pgdata-${SCALE}:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "$POSTGRES_PORT:5432" 
    command: >
      postgres
      -c max_wal_size=2GB
      -c checkpoint_timeout=15min
       
volumes:
  group12-pgdata-sf1:
   group12-pgdata-sf2:
  group12-pgdata-sf5: