version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
    - .env
    volumes:
      - ./schemas:/schemas
      - ./init:/docker-entrypoint-initdb.d
      - ./data/${SCALE}/:/data
      - ./queries/${SCALE}/:/queries
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    command: >
      postgres
      -c max_wal_size=2GB
      -c checkpoint_timeout=15min
       
volumes:
  pgdata: